rancher:
  replicas: 1

  bootstrapPassword: admin123   # âš ï¸ en prod usa un Secret seguro

  hostname: rancher.local       # ğŸ‘ˆ este campo sigue siendo obligatorio en Rancher, pon algo dummy

  ingress:
    enabled: false              # ğŸ‘ˆ desactivamos Ingress

  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443

  persistence:
    enabled: true
    storageClass: do-block-storage
    accessModes:
      - ReadWriteOnce
    size: 5Gi
